{
 "title": "eRPC Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Network-level Requests",
   "type": "graph",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_received_total{}[30s])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket[1m])) by (le, project, network, category))",
     "legendFormat": "p50: {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_network_request_duration_seconds_bucket[1m])) by (le, project, network, category))",
     "legendFormat": "p95: {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket[1m])) by (le, project, network, category))",
     "legendFormat": "p99: {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Errors",
   "type": "graph",
   "description": "When a request fails even after trying all upstreams and retries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_network_failed_request_total{}[1m])) by (project, network, upstream, error)",
     "legendFormat": "{{project}}, {{network}}, {{error}}"
    }
   ]
  },
  {
   "title": "Network self-imposed Rate-limited requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_self_rate_limited_total{}[1m])) by (project, network)",
     "legendFormat": "{{project}}, {{network}}"
    }
   ]
  },
  {
   "title": "Network-level Multiplexed requests",
   "type": "graph",
   "description": "When identical requests arrive at the same time they'll be merged, this number shows number of these requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_network_multiplexed_request_total{}[1m])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level cache Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_network_cache_hits_total{}[1m])) by (project, network, category)",
     "legendFormat": "Hits - {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "sum(rate(erpc_network_cache_misses_total{}[1m])) by (project, network, category)",
     "legendFormat": "Misses - {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level Requests",
   "type": "graph",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_total{}[1m])) by (project, network, upstream, category)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level Errors",
   "type": "graph",
   "description": "Failures received when attempting upstream endpoints, either errors returned in response or other failures while attempting the request",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_errors_total{}[1m])) by (project, network, upstream, error)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket[1m])) by (le, project, network, upstream, category))",
     "legendFormat": "p50: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket[1m])) by (le, project, network, upstream, category))",
     "legendFormat": "p95: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket[1m])) by (le, project, network, upstream, category))",
     "legendFormat": "p99: {{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level self-imposed Ratel-limited requests",
   "type": "graph",
   "description": "Total requests rate-limited locally on eRPC before actually sending, based on defined budget",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_self_rate_limited_total{}[1m])) by (project, network, upstream)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level Remote rate-limited Requests",
   "type": "graph",
   "description": "Total requests that are sent to upstream but is rate-limited by the provider node",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_remote_rate_limited_total{}[1m])) by (project, network, upstream)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  }
 ]
}